
deployments:
- instanceName : "my-app"
  valueFile: "value-dev.yaml"
  targetCluster: "dev-01"
  env: "dev"
  pathToProd: true
- instanceName : "my-app-feature-1"
  valueFile: "value-dev-feature-1.yaml"
  targetCluster: "dev-01"
  env: "dev"
- instanceName: "my-app-preprod"
  valueFile: "value-preprod.yaml"
  targetCluster: "prod-01"
  env: "preprod"
  pathToProd: true
- instanceName: "my-app-demo"
  valueFile: "value-demo.yaml"
  targetCluster: "prod-01"
  env: "preprod"
- instanceName: "my-app-prod"
  valueFile: "value-prod.yaml"
  targetCluster: "prod-01"
  env: "prod"
- instanceName: "my-app-prod-02"
  valueFile: "value-prod-02.yaml"
  targetCluster: "prod-01"
  env: "prod"
- instanceName: "my-app-prod-03"
  valueFile: "value-prod-03.yaml"
  targetCluster: "prod-01"
  env: "prod"


